################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../source/BitStream.cpp \
../source/CCRakNetSlidingWindow.cpp \
../source/CCRakNetUDT.cpp \
../source/CheckSum.cpp \
../source/CloudClient.cpp \
../source/CloudCommon.cpp \
../source/CloudServer.cpp \
../source/CommandParserInterface.cpp \
../source/ConnectionGraph2.cpp \
../source/ConsoleServer.cpp \
../source/DS_BytePool.cpp \
../source/DS_ByteQueue.cpp \
../source/DS_HuffmanEncodingTree.cpp \
../source/DS_Table.cpp \
../source/DataCompressor.cpp \
../source/DirectoryDeltaTransfer.cpp \
../source/DynDNS.cpp \
../source/EmailSender.cpp \
../source/EncodeClassName.cpp \
../source/EpochTimeToString.cpp \
../source/FileList.cpp \
../source/FileListTransfer.cpp \
../source/FileOperations.cpp \
../source/FormatString.cpp \
../source/FullyConnectedMesh2.cpp \
../source/GetTime.cpp \
../source/Getche.cpp \
../source/Gets.cpp \
../source/GridSectorizer.cpp \
../source/HTTPConnection.cpp \
../source/IncrementalReadInterface.cpp \
../source/Itoa.cpp \
../source/LinuxStrings.cpp \
../source/LocklessTypes.cpp \
../source/LogCommandParser.cpp \
../source/MessageFilter.cpp \
../source/NatPunchthroughClient.cpp \
../source/NatPunchthroughServer.cpp \
../source/NatTypeDetectionClient.cpp \
../source/NatTypeDetectionCommon.cpp \
../source/NatTypeDetectionServer.cpp \
../source/NetworkIDManager.cpp \
../source/NetworkIDObject.cpp \
../source/PacketConsoleLogger.cpp \
../source/PacketFileLogger.cpp \
../source/PacketLogger.cpp \
../source/PacketOutputWindowLogger.cpp \
../source/PacketizedTCP.cpp \
../source/PluginInterface2.cpp \
../source/RPC4Plugin.cpp \
../source/Rackspace.cpp \
../source/RakMemoryOverride.cpp \
../source/RakNetCommandParser.cpp \
../source/RakNetSocket.cpp \
../source/RakNetStatistics.cpp \
../source/RakNetTransport2.cpp \
../source/RakNetTypes.cpp \
../source/RakPeer.cpp \
../source/RakSleep.cpp \
../source/RakString.cpp \
../source/RakThread.cpp \
../source/RakWString.cpp \
../source/Rand.cpp \
../source/ReadyEvent.cpp \
../source/ReliabilityLayer.cpp \
../source/ReplicaManager3.cpp \
../source/Router2.cpp \
../source/SHA1.cpp \
../source/SecureHandshake.cpp \
../source/SendToThread.cpp \
../source/SignaledEvent.cpp \
../source/SimpleMutex.cpp \
../source/SocketLayer.cpp \
../source/StringCompressor.cpp \
../source/StringTable.cpp \
../source/SuperFastHash.cpp \
../source/TCPInterface.cpp \
../source/TableSerializer.cpp \
../source/TeamBalancer.cpp \
../source/TelnetTransport.cpp \
../source/ThreadsafePacketLogger.cpp \
../source/TwoWayAuthentication.cpp \
../source/UDPForwarder.cpp \
../source/UDPProxyClient.cpp \
../source/UDPProxyCoordinator.cpp \
../source/UDPProxyServer.cpp \
../source/VariableDeltaSerializer.cpp \
../source/VariableListDeltaTracker.cpp \
../source/VariadicSQLParser.cpp \
../source/VitaIncludes.cpp \
../source/WSAStartupSingleton.cpp \
../source/_FindFirst.cpp \
../source/gettimeofday.cpp \
../source/rdlmalloc.cpp 

OBJS += \
./source/BitStream.o \
./source/CCRakNetSlidingWindow.o \
./source/CCRakNetUDT.o \
./source/CheckSum.o \
./source/CloudClient.o \
./source/CloudCommon.o \
./source/CloudServer.o \
./source/CommandParserInterface.o \
./source/ConnectionGraph2.o \
./source/ConsoleServer.o \
./source/DS_BytePool.o \
./source/DS_ByteQueue.o \
./source/DS_HuffmanEncodingTree.o \
./source/DS_Table.o \
./source/DataCompressor.o \
./source/DirectoryDeltaTransfer.o \
./source/DynDNS.o \
./source/EmailSender.o \
./source/EncodeClassName.o \
./source/EpochTimeToString.o \
./source/FileList.o \
./source/FileListTransfer.o \
./source/FileOperations.o \
./source/FormatString.o \
./source/FullyConnectedMesh2.o \
./source/GetTime.o \
./source/Getche.o \
./source/Gets.o \
./source/GridSectorizer.o \
./source/HTTPConnection.o \
./source/IncrementalReadInterface.o \
./source/Itoa.o \
./source/LinuxStrings.o \
./source/LocklessTypes.o \
./source/LogCommandParser.o \
./source/MessageFilter.o \
./source/NatPunchthroughClient.o \
./source/NatPunchthroughServer.o \
./source/NatTypeDetectionClient.o \
./source/NatTypeDetectionCommon.o \
./source/NatTypeDetectionServer.o \
./source/NetworkIDManager.o \
./source/NetworkIDObject.o \
./source/PacketConsoleLogger.o \
./source/PacketFileLogger.o \
./source/PacketLogger.o \
./source/PacketOutputWindowLogger.o \
./source/PacketizedTCP.o \
./source/PluginInterface2.o \
./source/RPC4Plugin.o \
./source/Rackspace.o \
./source/RakMemoryOverride.o \
./source/RakNetCommandParser.o \
./source/RakNetSocket.o \
./source/RakNetStatistics.o \
./source/RakNetTransport2.o \
./source/RakNetTypes.o \
./source/RakPeer.o \
./source/RakSleep.o \
./source/RakString.o \
./source/RakThread.o \
./source/RakWString.o \
./source/Rand.o \
./source/ReadyEvent.o \
./source/ReliabilityLayer.o \
./source/ReplicaManager3.o \
./source/Router2.o \
./source/SHA1.o \
./source/SecureHandshake.o \
./source/SendToThread.o \
./source/SignaledEvent.o \
./source/SimpleMutex.o \
./source/SocketLayer.o \
./source/StringCompressor.o \
./source/StringTable.o \
./source/SuperFastHash.o \
./source/TCPInterface.o \
./source/TableSerializer.o \
./source/TeamBalancer.o \
./source/TelnetTransport.o \
./source/ThreadsafePacketLogger.o \
./source/TwoWayAuthentication.o \
./source/UDPForwarder.o \
./source/UDPProxyClient.o \
./source/UDPProxyCoordinator.o \
./source/UDPProxyServer.o \
./source/VariableDeltaSerializer.o \
./source/VariableListDeltaTracker.o \
./source/VariadicSQLParser.o \
./source/VitaIncludes.o \
./source/WSAStartupSingleton.o \
./source/_FindFirst.o \
./source/gettimeofday.o \
./source/rdlmalloc.o 

CPP_DEPS += \
./source/BitStream.d \
./source/CCRakNetSlidingWindow.d \
./source/CCRakNetUDT.d \
./source/CheckSum.d \
./source/CloudClient.d \
./source/CloudCommon.d \
./source/CloudServer.d \
./source/CommandParserInterface.d \
./source/ConnectionGraph2.d \
./source/ConsoleServer.d \
./source/DS_BytePool.d \
./source/DS_ByteQueue.d \
./source/DS_HuffmanEncodingTree.d \
./source/DS_Table.d \
./source/DataCompressor.d \
./source/DirectoryDeltaTransfer.d \
./source/DynDNS.d \
./source/EmailSender.d \
./source/EncodeClassName.d \
./source/EpochTimeToString.d \
./source/FileList.d \
./source/FileListTransfer.d \
./source/FileOperations.d \
./source/FormatString.d \
./source/FullyConnectedMesh2.d \
./source/GetTime.d \
./source/Getche.d \
./source/Gets.d \
./source/GridSectorizer.d \
./source/HTTPConnection.d \
./source/IncrementalReadInterface.d \
./source/Itoa.d \
./source/LinuxStrings.d \
./source/LocklessTypes.d \
./source/LogCommandParser.d \
./source/MessageFilter.d \
./source/NatPunchthroughClient.d \
./source/NatPunchthroughServer.d \
./source/NatTypeDetectionClient.d \
./source/NatTypeDetectionCommon.d \
./source/NatTypeDetectionServer.d \
./source/NetworkIDManager.d \
./source/NetworkIDObject.d \
./source/PacketConsoleLogger.d \
./source/PacketFileLogger.d \
./source/PacketLogger.d \
./source/PacketOutputWindowLogger.d \
./source/PacketizedTCP.d \
./source/PluginInterface2.d \
./source/RPC4Plugin.d \
./source/Rackspace.d \
./source/RakMemoryOverride.d \
./source/RakNetCommandParser.d \
./source/RakNetSocket.d \
./source/RakNetStatistics.d \
./source/RakNetTransport2.d \
./source/RakNetTypes.d \
./source/RakPeer.d \
./source/RakSleep.d \
./source/RakString.d \
./source/RakThread.d \
./source/RakWString.d \
./source/Rand.d \
./source/ReadyEvent.d \
./source/ReliabilityLayer.d \
./source/ReplicaManager3.d \
./source/Router2.d \
./source/SHA1.d \
./source/SecureHandshake.d \
./source/SendToThread.d \
./source/SignaledEvent.d \
./source/SimpleMutex.d \
./source/SocketLayer.d \
./source/StringCompressor.d \
./source/StringTable.d \
./source/SuperFastHash.d \
./source/TCPInterface.d \
./source/TableSerializer.d \
./source/TeamBalancer.d \
./source/TelnetTransport.d \
./source/ThreadsafePacketLogger.d \
./source/TwoWayAuthentication.d \
./source/UDPForwarder.d \
./source/UDPProxyClient.d \
./source/UDPProxyCoordinator.d \
./source/UDPProxyServer.d \
./source/VariableDeltaSerializer.d \
./source/VariableListDeltaTracker.d \
./source/VariadicSQLParser.d \
./source/VitaIncludes.d \
./source/WSAStartupSingleton.d \
./source/_FindFirst.d \
./source/gettimeofday.d \
./source/rdlmalloc.d 


# Each subdirectory must supply rules for building sources it contributes
source/%.o: ../source/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -I/home/aaaa/workspace/Server/src/CPlus/RakNetStaticSDK/include -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


