################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/Base64Encoder.cpp \
../src/BitStream.cpp \
../src/CCRakNetSlidingWindow.cpp \
../src/CCRakNetUDT.cpp \
../src/CheckSum.cpp \
../src/CloudClient.cpp \
../src/CloudCommon.cpp \
../src/CloudServer.cpp \
../src/CommandParserInterface.cpp \
../src/ConnectionGraph2.cpp \
../src/ConsoleServer.cpp \
../src/DS_BytePool.cpp \
../src/DS_ByteQueue.cpp \
../src/DS_HuffmanEncodingTree.cpp \
../src/DS_Table.cpp \
../src/DataCompressor.cpp \
../src/DirectoryDeltaTransfer.cpp \
../src/DynDNS.cpp \
../src/EmailSender.cpp \
../src/EncodeClassName.cpp \
../src/EpochTimeToString.cpp \
../src/FileList.cpp \
../src/FileListTransfer.cpp \
../src/FileOperations.cpp \
../src/FormatString.cpp \
../src/FullyConnectedMesh2.cpp \
../src/GetTime.cpp \
../src/Getche.cpp \
../src/Gets.cpp \
../src/GridSectorizer.cpp \
../src/HTTPConnection.cpp \
../src/HTTPConnection2.cpp \
../src/IncrementalReadInterface.cpp \
../src/Itoa.cpp \
../src/LinuxStrings.cpp \
../src/LocklessTypes.cpp \
../src/LogCommandParser.cpp \
../src/MessageFilter.cpp \
../src/NatPunchthroughClient.cpp \
../src/NatPunchthroughServer.cpp \
../src/NatTypeDetectionClient.cpp \
../src/NatTypeDetectionCommon.cpp \
../src/NatTypeDetectionServer.cpp \
../src/NetworkIDManager.cpp \
../src/NetworkIDObject.cpp \
../src/PacketConsoleLogger.cpp \
../src/PacketFileLogger.cpp \
../src/PacketLogger.cpp \
../src/PacketOutputWindowLogger.cpp \
../src/PacketizedTCP.cpp \
../src/PluginInterface2.cpp \
../src/RPC4Plugin.cpp \
../src/Rackspace.cpp \
../src/RakMemoryOverride.cpp \
../src/RakNetCommandParser.cpp \
../src/RakNetSocket.cpp \
../src/RakNetSocket2.cpp \
../src/RakNetSocket2_360_720.cpp \
../src/RakNetSocket2_Berkley.cpp \
../src/RakNetSocket2_NativeClient.cpp \
../src/RakNetSocket2_PS3_PS4.cpp \
../src/RakNetSocket2_Vita.cpp \
../src/RakNetSocket2_Windows_Linux.cpp \
../src/RakNetSocket2_Windows_Linux_360.cpp \
../src/RakNetStatistics.cpp \
../src/RakNetTransport2.cpp \
../src/RakNetTypes.cpp \
../src/RakPeer.cpp \
../src/RakSleep.cpp \
../src/RakString.cpp \
../src/RakThread.cpp \
../src/RakWString.cpp \
../src/Rand.cpp \
../src/ReadyEvent.cpp \
../src/RelayPlugin.cpp \
../src/ReliabilityLayer.cpp \
../src/ReplicaManager3.cpp \
../src/Router2.cpp \
../src/SHA1.cpp \
../src/SecureHandshake.cpp \
../src/SendToThread.cpp \
../src/SignaledEvent.cpp \
../src/SimpleMutex.cpp \
../src/SocketLayer.cpp \
../src/StatisticsHistory.cpp \
../src/StringCompressor.cpp \
../src/StringTable.cpp \
../src/SuperFastHash.cpp \
../src/TCPInterface.cpp \
../src/TableSerializer.cpp \
../src/TeamBalancer.cpp \
../src/TeamManager.cpp \
../src/TelnetTransport.cpp \
../src/ThreadsafePacketLogger.cpp \
../src/TwoWayAuthentication.cpp \
../src/UDPForwarder.cpp \
../src/UDPProxyClient.cpp \
../src/UDPProxyCoordinator.cpp \
../src/UDPProxyServer.cpp \
../src/VariableDeltaSerializer.cpp \
../src/VariableListDeltaTracker.cpp \
../src/VariadicSQLParser.cpp \
../src/VitaIncludes.cpp \
../src/WSAStartupSingleton.cpp \
../src/_FindFirst.cpp \
../src/gettimeofday.cpp 

OBJS += \
./src/Base64Encoder.o \
./src/BitStream.o \
./src/CCRakNetSlidingWindow.o \
./src/CCRakNetUDT.o \
./src/CheckSum.o \
./src/CloudClient.o \
./src/CloudCommon.o \
./src/CloudServer.o \
./src/CommandParserInterface.o \
./src/ConnectionGraph2.o \
./src/ConsoleServer.o \
./src/DS_BytePool.o \
./src/DS_ByteQueue.o \
./src/DS_HuffmanEncodingTree.o \
./src/DS_Table.o \
./src/DataCompressor.o \
./src/DirectoryDeltaTransfer.o \
./src/DynDNS.o \
./src/EmailSender.o \
./src/EncodeClassName.o \
./src/EpochTimeToString.o \
./src/FileList.o \
./src/FileListTransfer.o \
./src/FileOperations.o \
./src/FormatString.o \
./src/FullyConnectedMesh2.o \
./src/GetTime.o \
./src/Getche.o \
./src/Gets.o \
./src/GridSectorizer.o \
./src/HTTPConnection.o \
./src/HTTPConnection2.o \
./src/IncrementalReadInterface.o \
./src/Itoa.o \
./src/LinuxStrings.o \
./src/LocklessTypes.o \
./src/LogCommandParser.o \
./src/MessageFilter.o \
./src/NatPunchthroughClient.o \
./src/NatPunchthroughServer.o \
./src/NatTypeDetectionClient.o \
./src/NatTypeDetectionCommon.o \
./src/NatTypeDetectionServer.o \
./src/NetworkIDManager.o \
./src/NetworkIDObject.o \
./src/PacketConsoleLogger.o \
./src/PacketFileLogger.o \
./src/PacketLogger.o \
./src/PacketOutputWindowLogger.o \
./src/PacketizedTCP.o \
./src/PluginInterface2.o \
./src/RPC4Plugin.o \
./src/Rackspace.o \
./src/RakMemoryOverride.o \
./src/RakNetCommandParser.o \
./src/RakNetSocket.o \
./src/RakNetSocket2.o \
./src/RakNetSocket2_360_720.o \
./src/RakNetSocket2_Berkley.o \
./src/RakNetSocket2_NativeClient.o \
./src/RakNetSocket2_PS3_PS4.o \
./src/RakNetSocket2_Vita.o \
./src/RakNetSocket2_Windows_Linux.o \
./src/RakNetSocket2_Windows_Linux_360.o \
./src/RakNetStatistics.o \
./src/RakNetTransport2.o \
./src/RakNetTypes.o \
./src/RakPeer.o \
./src/RakSleep.o \
./src/RakString.o \
./src/RakThread.o \
./src/RakWString.o \
./src/Rand.o \
./src/ReadyEvent.o \
./src/RelayPlugin.o \
./src/ReliabilityLayer.o \
./src/ReplicaManager3.o \
./src/Router2.o \
./src/SHA1.o \
./src/SecureHandshake.o \
./src/SendToThread.o \
./src/SignaledEvent.o \
./src/SimpleMutex.o \
./src/SocketLayer.o \
./src/StatisticsHistory.o \
./src/StringCompressor.o \
./src/StringTable.o \
./src/SuperFastHash.o \
./src/TCPInterface.o \
./src/TableSerializer.o \
./src/TeamBalancer.o \
./src/TeamManager.o \
./src/TelnetTransport.o \
./src/ThreadsafePacketLogger.o \
./src/TwoWayAuthentication.o \
./src/UDPForwarder.o \
./src/UDPProxyClient.o \
./src/UDPProxyCoordinator.o \
./src/UDPProxyServer.o \
./src/VariableDeltaSerializer.o \
./src/VariableListDeltaTracker.o \
./src/VariadicSQLParser.o \
./src/VitaIncludes.o \
./src/WSAStartupSingleton.o \
./src/_FindFirst.o \
./src/gettimeofday.o 

CPP_DEPS += \
./src/Base64Encoder.d \
./src/BitStream.d \
./src/CCRakNetSlidingWindow.d \
./src/CCRakNetUDT.d \
./src/CheckSum.d \
./src/CloudClient.d \
./src/CloudCommon.d \
./src/CloudServer.d \
./src/CommandParserInterface.d \
./src/ConnectionGraph2.d \
./src/ConsoleServer.d \
./src/DS_BytePool.d \
./src/DS_ByteQueue.d \
./src/DS_HuffmanEncodingTree.d \
./src/DS_Table.d \
./src/DataCompressor.d \
./src/DirectoryDeltaTransfer.d \
./src/DynDNS.d \
./src/EmailSender.d \
./src/EncodeClassName.d \
./src/EpochTimeToString.d \
./src/FileList.d \
./src/FileListTransfer.d \
./src/FileOperations.d \
./src/FormatString.d \
./src/FullyConnectedMesh2.d \
./src/GetTime.d \
./src/Getche.d \
./src/Gets.d \
./src/GridSectorizer.d \
./src/HTTPConnection.d \
./src/HTTPConnection2.d \
./src/IncrementalReadInterface.d \
./src/Itoa.d \
./src/LinuxStrings.d \
./src/LocklessTypes.d \
./src/LogCommandParser.d \
./src/MessageFilter.d \
./src/NatPunchthroughClient.d \
./src/NatPunchthroughServer.d \
./src/NatTypeDetectionClient.d \
./src/NatTypeDetectionCommon.d \
./src/NatTypeDetectionServer.d \
./src/NetworkIDManager.d \
./src/NetworkIDObject.d \
./src/PacketConsoleLogger.d \
./src/PacketFileLogger.d \
./src/PacketLogger.d \
./src/PacketOutputWindowLogger.d \
./src/PacketizedTCP.d \
./src/PluginInterface2.d \
./src/RPC4Plugin.d \
./src/Rackspace.d \
./src/RakMemoryOverride.d \
./src/RakNetCommandParser.d \
./src/RakNetSocket.d \
./src/RakNetSocket2.d \
./src/RakNetSocket2_360_720.d \
./src/RakNetSocket2_Berkley.d \
./src/RakNetSocket2_NativeClient.d \
./src/RakNetSocket2_PS3_PS4.d \
./src/RakNetSocket2_Vita.d \
./src/RakNetSocket2_Windows_Linux.d \
./src/RakNetSocket2_Windows_Linux_360.d \
./src/RakNetStatistics.d \
./src/RakNetTransport2.d \
./src/RakNetTypes.d \
./src/RakPeer.d \
./src/RakSleep.d \
./src/RakString.d \
./src/RakThread.d \
./src/RakWString.d \
./src/Rand.d \
./src/ReadyEvent.d \
./src/RelayPlugin.d \
./src/ReliabilityLayer.d \
./src/ReplicaManager3.d \
./src/Router2.d \
./src/SHA1.d \
./src/SecureHandshake.d \
./src/SendToThread.d \
./src/SignaledEvent.d \
./src/SimpleMutex.d \
./src/SocketLayer.d \
./src/StatisticsHistory.d \
./src/StringCompressor.d \
./src/StringTable.d \
./src/SuperFastHash.d \
./src/TCPInterface.d \
./src/TableSerializer.d \
./src/TeamBalancer.d \
./src/TeamManager.d \
./src/TelnetTransport.d \
./src/ThreadsafePacketLogger.d \
./src/TwoWayAuthentication.d \
./src/UDPForwarder.d \
./src/UDPProxyClient.d \
./src/UDPProxyCoordinator.d \
./src/UDPProxyServer.d \
./src/VariableDeltaSerializer.d \
./src/VariableListDeltaTracker.d \
./src/VariadicSQLParser.d \
./src/VitaIncludes.d \
./src/WSAStartupSingleton.d \
./src/_FindFirst.d \
./src/gettimeofday.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -I../include -O0 -g3 -Wall -m64 -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


