/*
 * errordefine.h
 *
 *  Created on: 2017年4月9日
 *      Author: aaaa
 */

#ifndef ERRORDEFINE_H_
#define ERRORDEFINE_H_



//登陆错误原因
enum ERROR_LOGIN
{
	ERR_LOGIN_SUCCEED,
	ERR_LOGIN_ID,
	ERR_LOGIN_PSW,
	ERR_LOGIN_ONLINE,
	ERR_LOGIN_ID_CANNOT_USE,//mx 2010.01.07 封停帐号
};

//注册错误原因
enum ERROR_REGISTER
{
	ERR_REGISTER_SUCCEED,
	ERR_REGISTER_ACCOUNT,
	ERR_REGISTER_DEARNAME,
	ERR_REGISTER_PASSWORD_NUM,
	ERR_REGISTER_PASSWORD_DIFFER,
	ERR_REGISTER_EMAIL,
	ERR_REGISTER_NOPEOPLE,
	ERR_REGISTER_CARDID,
	ERR_REGISTER_VALIDATE,
};

//好友错误
enum ERROR_FRIEND
{
	ERR_FRIEND_MAX,		//已达好友最大值
	ERR_FRIEND_ONLINE,	//对方不在线
	ERR_FRIEND_SET,		//对方已设置拒加所有好友
	ERR_FRIEND_REFUSE,  //对方拒绝加好友
	ERR_FRIEND_SUCCESS, //添加好友成功
};

//进入房间错误原因
enum ERROR_ENTERROOM
{
	ERR_ENTERROOM_ACCEPT,				//允许进入房间
	ERR_ENTERROOM_GAMEID,				//游戏id错误
	ERR_ENTERROOM_ROOMID,				//房间id错误
	ERR_ENTERROOM_FULL,					//房间已满(对于非VIP用户)
	ERR_ENTERROOM_FULLVIP,				//房间已满(对于VIP用户)
	ERR_ENTERROOM_NOTENOUGHBEAN,
	ERR_ENTERROOM_NOTENOUGHMONEY,
	ERR_ENTERROOM_MATCHING,				//正在比赛
	ERR_ENTERROOM_SYS_MANAGE,			//被系统托管
};

//银行错误
enum ERROR_BANK
{
	ERR_BANK_OVER,
	ERR_BANK_NOMONEY,
	ERR_BANK_INGAME,
};

//钱币转换错误原因
enum ERROR_CHANGE
{
	ERR_CHANGE_INGAME,
	ERR_CHANGE_SUCCESS,
	ERR_CHANGE_OVER,
	ERR_CHANGE_NOMONEY,
};

//进入桌子错误原因
enum ERROR_ENTERTABLE
{
	ERR_ENTERTABLE_ACCEPT,
	ERR_ENTERTABLE_TABLEID,				//桌子id错误
	ERR_ENTERTABLE_CHAIRID,				//椅子id错误
	ERR_ENTERTABLE_HAVEUSER,			//已经坐人了
	ERR_ENTERTABLE_NOTENOUGHBEAN,		//乐豆不够
	ERR_ENTERTABLE_NOTENOUGHMONEY,		//金币不够
	ERR_ENTERTABLE_INGAME,				//已经在游戏中
	ERR_ENTERTABLE_PASSWORD,			//密码错

	ERR_ENTERTABLE_HAVE_SAMEIP,			//有ip相同
	ERR_ENTERTABLE_HAVE_DISCONNECT,		//有断线率大的
	ERR_ENTERTABLE_HAVE_SCOREDIS,		//有分差大的
	ERR_ENTERTABLE_HAVE_SCOREMIN,		//有分小的

	ERR_ENTERTABLE_YOU_SAMEIP,			//自己和桌子上ip相同
	ERR_ENTERTABLE_YOU_DISCONNECT,		//自己断线大
	ERR_ENTERTABLE_YOU_SCOREDIS,		//自己分差大
	ERR_ENTERTABLE_YOU_SCOREMIN,		//自己分小

	ERR_ENTERTABLE_NOWELCOME,			//不受欢迎

	ERR_ENTERROOM_LOOKAT,				//旁观
};

//强制离开房间原因
enum ERROR_FORCE_LEAVE_ROOM
{
	ERR_FORCE_LEAVE_ROOM_NOTENOUGHBEAN,				//没有足够乐豆
	ERR_FORCE_LEAVE_ROOM_NOTENOUGHMONEY,			//没有足够金币
	ERR_FORCE_LEAVE_ROOM_DISCONNECT,				//断线
	ERR_FORCE_LEAVE_ROOM_MATCHEND,					//比赛结束
	ERR_FORCE_LEAVE_ROOM_UNREADY,					//未准备	ADD BY QIAOLEI
	ERR_FORCE_LEAVE_ROOM_SYSMANAGE,					//系统托管  add by mx
};

enum ERROR_MATCH_SIGN_UP
{
	ERR_SIGNUP_ACCEPT,//报名成功
	ERR_SIGNUP_TRUE,//已经报过名
	ERR_SIGNUP_NOMONEY,//报名费不够
	ERR_NO_SIGNUP,//该房间不允许报名
	ERR_SIGNUP_FULL,//报名人满

	ERR_NO_ENOUGH_MONEY,
	ERR_NO_ENOUGH_LEDOU,
	ERR_NO_ENOUGH_ROSE,
	ERR_NO_ENOUGH_HONOR,
	ERR_NO_ENOUGH_CHARM,

	ERR_NO_PLACE,									//预赛的名次不够
	ERR_NO_PLACEEX,									//没有资格参加大奖赛总决赛

	ERR_NO_GRADE,							//等级不符。
	ERR_NO_REALSEX,							//不是女性认证。
	ERR_NO_VIP,								//不是ＶＩＰ。
	ERR_NO_CHARM,							//魅力不符。
	ERR_NO_TICKET,							//竞赛券不够。
	ERR_NO_MONEY,							//钱不够。
	ERR_NO_HONOR,							//勋章不够。
	ERR_NO_IP,								//ＩＰ不符。

};
enum ERROR_MATCH_EXIT
{
	ERR_MATCH_EXIT_NO_SIGNUP,				//没有报名
	ERR_MATCH_EXIT_BEGINED,					//比赛已开始
	ERR_MATCH_EXIT_ACCESS,					//退赛成功
};




#endif /* ERRORDEFINE_H_ */
